### ISSUE TITLE
Syntax Error when using Rollup

### ISSUE THREAD

**Issue by Isaac-Tait** [phptuts/Svelte-PrismJS#2]
When I am testing locally I am returning this error:

```
ParseError: /node_modules/prismjs/plugins/line-numbers/prism-line-numbers.css
SyntaxError: Unexpected token (1:9)
    pre[class*="language-"].line-numbers {
             ^
    at compileModule (/Users/isaactait/Desktop/Web_Dev/sveltesociety.dev/node_modules/nollup/lib/impl/NollupCompiler.js:118:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async compileInputTarget (/Users/isaactait/Desktop/Web_Dev/sveltesociety.dev/node_modules/nollup/lib/impl/NollupCompiler.js:140:5)
    at async Object.compile (/Users/isaactait/Desktop/Web_Dev/sveltesociety.dev/node_modules/nollup/lib/impl/NollupCompiler.js:213:31)
    at async generateImpl (/Users/isaactait/Desktop/Web_Dev/sveltesociety.dev/node_modules/nollup/lib/index.js:13:21)
ParseError: /node_modules/prismjs/plugins/line-numbers/prism-line-numbers.css
SyntaxError: Unexpected token (1:9)
    pre[class*="language-"].line-numbers {
             ^
    at compileModule (/Users/isaactait/Desktop/Web_Dev/sveltesociety.dev/node_modules/nollup/lib/impl/NollupCompiler.js:118:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async compileInputTarget (/Users/isaactait/Desktop/Web_Dev/sveltesociety.dev/node_modules/nollup/lib/impl/NollupCompiler.js:140:5)
    at async Object.compile (/Users/isaactait/Desktop/Web_Dev/sveltesociety.dev/node_modules/nollup/lib/impl/NollupCompiler.js:213:31)
    at async generateImpl (/Users/isaactait/Desktop/Web_Dev/sveltesociety.dev/node_modules/nollup/lib/index.js:13:21)
ParseError: /node_modules/prismjs/plugins/line-numbers/prism-line-numbers.css
SyntaxError: Unexpected token (1:9)
    pre[class*="language-"].line-numbers {
             ^
    at compileModule (/Users/isaactait/Desktop/Web_Dev/sveltesociety.dev/node_modules/nollup/lib/impl/NollupCompiler.js:118:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async compileInputTarget (/Users/isaactait/Desktop/Web_Dev/sveltesociety.dev/node_modules/nollup/lib/impl/NollupCompiler.js:140:5)
    at async Object.compile (/Users/isaactait/Desktop/Web_Dev/sveltesociety.dev/node_modules/nollup/lib/impl/NollupCompiler.js:213:31)
    at async generateImpl (/Users/isaactait/Desktop/Web_Dev/sveltesociety.dev/node_modules/nollup/lib/index.js:13:21)
ParseError: /node_modules/prismjs/plugins/line-numbers/prism-line-numbers.css
SyntaxError: Unexpected token (1:9)
    pre[class*="language-"].line-numbers {
             ^
    at compileModule (/Users/isaactait/Desktop/Web_Dev/sveltesociety.dev/node_modules/nollup/lib/impl/NollupCompiler.js:118:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async compileInputTarget (/Users/isaactait/Desktop/Web_Dev/sveltesociety.dev/node_modules/nollup/lib/impl/NollupCompiler.js:140:5)
    at async Object.compile (/Users/isaactait/Desktop/Web_Dev/sveltesociety.dev/node_modules/nollup/lib/impl/NollupCompiler.js:213:31)
    at async generateImpl (/Users/isaactait/Desktop/Web_Dev/sveltesociety.dev/node_modules/nollup/lib/index.js:13:21)
```

I am following the Rollup Config install.

Any ideas on how to resolve would be greatly appreciated. Cheers.

**Comment by phptuts** [comment]
I just saw this I am going to take a look today!

Thank you

**Comment by Isaac-Tait** [comment]
To clarify I get this error if I do not go with the CDN option and instead run `npm install rollup-plugin-css-only` and add the code specified in the readme to the `rollup.config.js` file as well as the `main.js` and `index.html` files... 

If I go with the CDN option I get the blue highlight line to appear next to my code blocks but no line numbers (the same blue bar as seen on your Svelte app [site](https://phptuts.github.io/Svelte-PrismJS/index.html)).

**Comment by phptuts** [comment]
That's good to know

**Comment by phptuts** [comment]
I think I fixed it.  Can you try it out

**Comment by Isaac-Tait** [comment]
@phptuts It looks like the update has not propagated to [NPM](https://www.npmjs.com/package/svelte-prismjs) yet? It still shows `1.0.1` as the current version and running `npm update svelte-prismjs` does not update either (I also tried uninstalling and reinstalling and it still loads `1.0.1`...

**Comment by phptuts** [comment]
My bad I forgot to publish it.  It should be up now.

**Comment by phptuts** [comment]
@Isaac-Tait did that work for you can we close this issue?

**Comment by phptuts** [comment]
Awesome thank you

**Comment by Isaac-Tait** [comment]
I am out camping in the mountains with super spotty reception. I will assess when I return. In the meantime go ahead and close the issue. I am sure you fixed it. I am excited to give it a shot when I get home 😎
